### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by darinhouston** [richinfante/iphonebackuptools#51] opened 2019-10-05 05:44 UTC
npm is installed -- installed node -- but can't get ibackuptool installed.  

OSX 10.11.6

/usr/local/bin/ibackuptool -> /usr/local/lib/node_modules/ibackuptool/tools/cli.js

> sqlite3@4.1.0 install /usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-pre-gyp: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/darin/.npm/_logs/2019-10-05T05_41_57_384Z-debug.log

**Comment by richinfante** [comment] 2019-10-06 15:13
closing - looks like a duplicate of #52, seems to be same permissions issue

**Closed by richinfante** 2019-10-06 15:13 UTC
